version: '3.8'

services:
  tax-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    volumes:
      - ./src:/app/src
    command: ["go", "run", "src/tax.go"]